### ISSUE TITLE
after trying it

### ISSUE THREAD

**Issue by Fraprwnt** [Bimby-Boi/qbx_bankrobbery#1]
### Summary

robbery

### Reproduction

1.when trying to open using a security card the door still doesn't open.
![image](https://github.com/Bimby-Boi/qbx_bankrobbery/assets/58946086/623356bf-5eda-44b6-b115-457f212fdef4)

2.When the script is restarted, this door is not locked again
![image](https://github.com/Bimby-Boi/qbx_bankrobbery/assets/58946086/2f96fd1b-27bb-40b0-a247-b7804fd29964)

3.Using thermite also can't be opened, even though I've done the minigame
![image](https://github.com/Bimby-Boi/qbx_bankrobbery/assets/58946086/b6209dce-5e1e-4699-80bf-a10a97c6ea9e)

all doors cannot be opened except the ones using the lockpick at the start. at a big bank

### Expected behavior

....

### Actual behavior

....

### Additional context

...

### Current Version

...

### Custom Resources

...

**Comment by Fraprwnt** [comment]
the safe on the laptop doesn't work when you click, nothing comes out

**Comment by Bimby-Boi** [comment]
as far as your gates not opening after thermite/redcard thats likely due to your doorlock IDs. Make sure that the ID in your ox_doorlok DB matches the doorID in config > shared.lua. 
For an example. In the shared.lua: PAcific standard thermite door 1 has a doorID of 2, that needs to match the ox_doorlock database ID. If the ID is different in your DB make the number match in the shared.lua.

as far as the first gate in big bank not resetting after a resource restart, thats because its just controlled by ox_doorlock. it resets after 30 minutes or can be locked by police. You can shorten the autolock time in the ox_door command, but I left it long so theres no change of criminals getting locked in unless they really suck at the heist.

"the safe on the laptop doesn't work when you click, nothing comes out"
I have no idea what you mean by that. What laptop?

**Comment by Bimby-Boi** [comment]
![id example](https://github.com/Bimby-Boi/qbx_bankrobbery/assets/164100440/d5b96cee-8e8d-412d-aa58-4cce08713794)
heres an image showing the shared.lua doorID and ox_doorlock DB id.
They need to match

**Comment by Bimby-Boi** [comment]
![image_2024-03-20_110653943](https://github.com/Bimby-Boi/qbx_bankrobbery/assets/164100440/8332d94e-b134-4b46-8592-b4100a0193d9)
also, just incase: the redcard door is client > pacific.lua line 46
make sure that matches the ox_doorlock db ID as well.

**Comment by Bimby-Boi** [comment]
![image_2024-03-20_112006902](https://github.com/Bimby-Boi/qbx_bankrobbery/assets/164100440/724a3c88-8245-49ee-a57d-dd2931976f65)
I just tested it, so it should be working as long as your db IDs and doorIDs match

**Comment by Bimby-Boi** [comment]
turns out I forgot to edit the server file... my bad

RegisterNetEvent("qbx_bankrobbery:server:OpenGate", function(currentGate, state)
exports.ox_doorlock:setDoorState(currentGate, state)
end)

server > main.lia 
I added it at line 411 or just redownload the script
should work now. Report back and let me know

**Comment by Fraprwnt** [comment]
The problem with doors using thermite is the same, but it still doesn't work, why? Then there's no notification of the door opening either.

**Comment by Bimby-Boi** [comment]
I've tested it multiple times and it works perfectly for me.
The only things that makes sense are either
A. You dont have the OpenGate event that I posted above/put in the server main.lua a few hours ago
or
B. Your doorID and database IDs are different
I'm not sure what else it could possibly be.

what is on github is whats on my server and as shown with pictures above the thermite doors unlock with no issues. Either my qbox version is different from yours in a vastly different way or you've messed up the install with doorIDs and ox_doorlock IDs.

**Comment by Bimby-Boi** [comment]
Also, saying "it doesnt work" is just shy of worthless. Post pics of your ox_doorlock DB, post the config > shared.lua doorIDs that may need changed, post a pic of server main.lua line 411 so I'm sure you even have the server event, maybe check the prints that should be printing in your f8 every time you use the thermite to make sure that number corresponds with your ox_doorlock DB. Help me help you.

**Comment by Fraprwnt** [comment]
Okay, maybe I will be more thorough later, maybe this is just my mistake.
